default: clearscreen main-quick

full: clearscreen main-full

flower: clearscreen main-flower

main-quick:
	@go run main.go rgb.png
	@echo ""
	@echo ""

main-flower:
	@go run main.go flower.jpg
	@echo ""
	@echo ""

main-full:
	@go run main.go
	@echo ""
	@echo ""

clean:
	rm -fr samples/autogenerated

clearscreen:
	@clear

gitpush:
	git push 
	git push --tags

gofmt:
	go fmt ./...
